name: Report Scam Links Seen In Comments
description: Report scam links, you have seen in the Youtube comment section
title: "Add scam link"
labels: ["scam-link"]
body:
  - type: markdown
    attributes:
      value: |      
        Please do not create a PR, to make it easier for review
  - type: dropdown
    id: filter-mode
    attributes:
      label: Link/Screenshot of spam comment
      description: Please provide a link to the spam comment with the scam link, or a screenshot, preferably a link though.
      placeholder: (Screenshots can be attached by dragging and dropping image files here)
    validations:
      required: true
  - type: textarea
    id: video-link
    attributes:
      label: Scam website link
      description: A link of the scam website, the bot/user mentioned in the comment
  - type: textarea
    id: additional-context
    attributes:
      label: (Optional) Additional Info / Context
      description: Other info that might be helpful, such as a description of why a comment is or is not spam.
      placeholder: Enter any extra info here
